from django.contrib import admin
from .models import *

admin.site.register(GivePursant)
admin.site.register(Pursant)
admin.site.register(IsMoshaver)
admin.site.register(UserOwner)
admin.site.register(Category)
admin.site.register(MlmProductMainCategories)
admin.site.register(MlmProductSubCategories_1)
admin.site.register(MlmProductSubCategories_2)
admin.site.register(MlmProducts)
admin.site.register(MlmProductsOrders)
admin.site.register(MlmProductsCarts)
admin.site.register(Copons)
admin.site.register(UserWalletRequest)
admin.site.register(Seminars)
admin.site.register(Catalogs)
admin.site.register(Ticket)
admin.site.register(Comments)
admin.site.register(ResponseC)
admin.site.register(DidacticFile)
admin.site.register(Offers)
admin.site.register(Consultation)
admin.site.register(ProductComment)
admin.site.register(Agency)
